[[redirects]]
  from = "https://damepanely.cz/<path-to-access-cors-url>"
  to = "https://lunastav.cz/api/raynet"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"