[[redirects]]
  from = "/api/raynet/"
  to = "https://lunastav.cz/api/raynet/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"